
stages:
  - docker-build
  - build
  - verification
  - deploy

build:images:
  stage: docker-build
  only: 
    - master
  script:
    - make -f docker.mk base-build
    - make -f docker.mk dev-build
    - make -f docker.mk try-build
  tags:
    - docker-shell

build:
  stage: build
  image: "otaviog/tensorviz-base:latest"
  script:
    - python setup.py develop
  artifacts:
    untracked: true
    expire_in: 1 week
  tags:
    - container

##
# Verification stage
linter:
  before_script:
    - python setup.py develop
    - pip install -r requirements-dev.txt
  needs: ["build"]
  image: "otaviog/tensorviz-base:latest"
  stage: verification
  script:
    - make -f tasks.mk pylint
  tags:
    - gpu-container

unit-test:
  before_script:
    - python setup.py develop
  needs: ["build"]
  image: "otaviog/tensorviz-base:latest"
  stage: verification
  script:
    - make -f unit-tests.mk all
  tags:
    - gpu-container

pages:
  image: "otaviog/tensorviz-base:latest"
  stage: deploy
  before_script:
    - apt update && DEBIAN_FRONTEND=noninteractive apt -yq install sudo doxygen graphviz
  script:
    - pip3 install -r requirements-dev.txt
    - make -f tasks.mk doc-create
    - cp -r doc/html public
    - make -f tasks.mk cpp-doc-create
    - cp -r doc/cpp/html public/cpp
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - container

dockerhub:
  stage: deploy
  only: 
    - master
  script:
    - make -f docker.mk try-push
  tags:
    - docker-shell
